# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hmenn/Workspace/CSE396_Proje2/CSE396-rasp-ali-recogner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hmenn/Workspace/CSE396_Proje2/CSE396-rasp-ali-recogner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hmenn/Workspace/CSE396_Proje2/CSE396-rasp-ali-recogner/CMakeFiles /home/hmenn/Workspace/CSE396_Proje2/CSE396-rasp-ali-recogner/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hmenn/Workspace/CSE396_Proje2/CSE396-rasp-ali-recogner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CSE396_rasp_ali_recogner

# Build rule for target.
CSE396_rasp_ali_recogner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CSE396_rasp_ali_recogner
.PHONY : CSE396_rasp_ali_recogner

# fast build rule for target.
CSE396_rasp_ali_recogner/fast:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/build
.PHONY : CSE396_rasp_ali_recogner/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/main.cpp.s
.PHONY : main.cpp.s

src/Communication.o: src/Communication.cpp.o

.PHONY : src/Communication.o

# target to build an object file
src/Communication.cpp.o:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/src/Communication.cpp.o
.PHONY : src/Communication.cpp.o

src/Communication.i: src/Communication.cpp.i

.PHONY : src/Communication.i

# target to preprocess a source file
src/Communication.cpp.i:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/src/Communication.cpp.i
.PHONY : src/Communication.cpp.i

src/Communication.s: src/Communication.cpp.s

.PHONY : src/Communication.s

# target to generate assembly for a file
src/Communication.cpp.s:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/src/Communication.cpp.s
.PHONY : src/Communication.cpp.s

src/ProccesImage.o: src/ProccesImage.cpp.o

.PHONY : src/ProccesImage.o

# target to build an object file
src/ProccesImage.cpp.o:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/src/ProccesImage.cpp.o
.PHONY : src/ProccesImage.cpp.o

src/ProccesImage.i: src/ProccesImage.cpp.i

.PHONY : src/ProccesImage.i

# target to preprocess a source file
src/ProccesImage.cpp.i:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/src/ProccesImage.cpp.i
.PHONY : src/ProccesImage.cpp.i

src/ProccesImage.s: src/ProccesImage.cpp.s

.PHONY : src/ProccesImage.s

# target to generate assembly for a file
src/ProccesImage.cpp.s:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/src/ProccesImage.cpp.s
.PHONY : src/ProccesImage.cpp.s

src/rs232.o: src/rs232.c.o

.PHONY : src/rs232.o

# target to build an object file
src/rs232.c.o:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/src/rs232.c.o
.PHONY : src/rs232.c.o

src/rs232.i: src/rs232.c.i

.PHONY : src/rs232.i

# target to preprocess a source file
src/rs232.c.i:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/src/rs232.c.i
.PHONY : src/rs232.c.i

src/rs232.s: src/rs232.c.s

.PHONY : src/rs232.s

# target to generate assembly for a file
src/rs232.c.s:
	$(MAKE) -f CMakeFiles/CSE396_rasp_ali_recogner.dir/build.make CMakeFiles/CSE396_rasp_ali_recogner.dir/src/rs232.c.s
.PHONY : src/rs232.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CSE396_rasp_ali_recogner"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Communication.o"
	@echo "... src/Communication.i"
	@echo "... src/Communication.s"
	@echo "... src/ProccesImage.o"
	@echo "... src/ProccesImage.i"
	@echo "... src/ProccesImage.s"
	@echo "... src/rs232.o"
	@echo "... src/rs232.i"
	@echo "... src/rs232.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

